version: '3'

services:
  plexsync:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: plex-sync
    environment:
      - "TZ=America/Toronto"
    restart: unless-stopped